dist: xenial
language: python
script:
  - nosetests
python:
  - 3.7.4
addons:
  apt:
    packages:
    - tesseract-ocr-eng
    - Package
install:
  - pip install -r requirements.txt
  - pip install nose
